### ISSUE TITLE
Call for participations - Event brite

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/okoa16#32]
Create an eventbrite event and span the call

**Comment by cristianolongo** [comment]
https://www.eventbrite.it/e/biglietti-open-knowledge-open-arts-2016-workshop-20725051186?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=esfb&utm-source=fb&utm-term=listing

**Comment by cristianolongo** [comment]
Inserire una doppia opzione per la cena sociale: light e full. In riferimento alla cena sociale, inserire un link alla pagina http://www.dmi.unict.it/~longo/okoa16/dinner.html .

Inserire opzione per il tour archeologico. In merito a questo inserire un riferimento alla pagina http://www.dmi.unict.it/~longo/okoa16/archeotour.html .

Inserire infine una richiesta per sapere se il partecipante ha bisogno dell'attestato di partecipazione.

**Comment by fabiorinnone** [comment]
Doppia opzione per cena sociale, opzione per tour archeologico e richiesta attestato di partecipazione inserite.

**Comment by cristianolongo** [comment]
Non vedo i link indicati al commento sopra

**Comment by fabiorinnone** [comment]
Devo inserire anche link al programma? Oltre che alle pagine del tour e della cena sociale?

Lo sto facendo, controlla se va bene e casomai modifico.

**Comment by fabiorinnone** [comment]
Il link al programma quello del sito, giusto? Mi pare di aver capito così dalla lunghissima discussione degli ultimi due giorni in cui mi sono perso quasi del tutto

**Comment by fabiorinnone** [comment]
Link al programma inserito.

**Comment by fabiorinnone** [comment]
Link cena sociale e tour inseriti.
