### ISSUE TITLE
Program in the web site

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/okoa16#35]

**Comment by cristianolongo** [comment]
[programme f351661]

**Comment by elisabonacini** [comment]
cristiano, scusa, dov'è il programma?

**Comment by cristianolongo** [comment]
Una preview è disponibile in http://www.dmi.unict.it/~longo/okoa16/index2.html, ma Carlo sta proponendo una versione lievemente modificata.

**Comment by cristianolongo** [comment]
[master 7922b5c] merged
